let itemList = [
    {"itemNo" : "gc1001" , "itemName" : "딸기 쥬얼리 벨벳 밀크티" , "itemPrice" : 4900, "itemGroup" : "smu"},//itemGroup - 아이템별 페이지 이름
    {"itemNo" : "gc1002" , "itemName" : "딸기 듬뿍 밀크티" , "itemPrice" : 4900, "itemGroup" : "smu"},
    {"itemNo" : "gc1003" , "itemName" : "얼그레이 딸기 스무디" , "itemPrice" : 4900, "itemGroup" : "smu"},
    {"itemNo" : "gc1004" , "itemName" : "블랙티 카페 스무디+펄" , "itemPrice" : 4000, "itemGroup" : "smu"},
    {"itemNo" : "gc1005" , "itemName" : "공차슈페너" , "itemPrice" : 4000, "itemGroup" : "smu"},
    {"itemNo" : "gc1006" , "itemName" : "얼그레이 카페라떼+펄" , "itemPrice" : 4500, "itemGroup" : "smu"},
    {"itemNo" : "gc1007" , "itemName" : "피스타치오 밀크티+펄" , "itemPrice" : 4400, "itemGroup" : "bmu"},
    {"itemNo" : "gc1008" , "itemName" : "타로 밀크티+펄" , "itemPrice" : 4000, "itemGroup" : "bmu"},
    {"itemNo" : "gc1009" , "itemName" : "블랙 밀크티+펄" , "itemPrice" : 3900, "itemGroup" : "bmu"},
    {"itemNo" : "gc1010" , "itemName" : "청포도 그린티+알로에" , "itemPrice" : 4100, "itemGroup" : "bmu"},
    {"itemNo" : "gc1011" , "itemName" : "망고요구르트+화이트펄" , "itemPrice" : 4200, "itemGroup" : "bmu"},
    {"itemNo" : "gc1012" , "itemName" : "제주 그린 밀크티+펄" , "itemPrice" : 4400, "itemGroup" : "bmu"},
    {"itemNo" : "gc1013" , "itemName" : "블랙 밀크티" , "itemPrice" : 3400, "itemGroup" : "mik"},
    {"itemNo" : "gc1014" , "itemName" : "얼그레이 밀크티" , "itemPrice" : 3300, "itemGroup" : "mik"},
    {"itemNo" : "gc1015" , "itemName" : "타로 밀크티" , "itemPrice" : 3500, "itemGroup" : "mik"},
    {"itemNo" : "gc1016" , "itemName" : "우롱 밀크티" , "itemPrice" : 3400, "itemGroup" : "mik"},
    {"itemNo" : "gc1017" , "itemName" : "피스타치오 밀크티" , "itemPrice" : 3900, "itemGroup" : "mik"},
    {"itemNo" : "gc1018" , "itemName" : "제주 그린 밀크티" , "itemPrice" : 3900, "itemGroup" : "mik"},
    {"itemNo" : "gc1019" , "itemName" : "하동 호지 밀크티" , "itemPrice" : 3800, "itemGroup" : "mik"},
    {"itemNo" : "gc1020" , "itemName" : "초콜렛 밀크티" , "itemPrice" : 3600, "itemGroup" : "mik"},
    {"itemNo" : "gc1021" , "itemName" : "자스민 그린 밀크티" , "itemPrice" : 3700, "itemGroup" : "mik"},
    {"itemNo" : "gc1022" , "itemName" : "우롱티" , "itemPrice" : 3200, "itemGroup" : "ori"},
    {"itemNo" : "gc1023" , "itemName" : "자스민 그린티" , "itemPrice" : 3300, "itemGroup" : "ori"},
    {"itemNo" : "gc1024" , "itemName" : "블랙티" , "itemPrice" : 3300, "itemGroup" : "ori"},
    {"itemNo" : "gc1025" , "itemName" : "얼그레이티" , "itemPrice" : 3400, "itemGroup" : "ori"},
    {"itemNo" : "gc1026" , "itemName" : "펄" , "itemPrice" : 500, "itemGroup" : "sub"},
    {"itemNo" : "gc1027" , "itemName" : "밀크폼" , "itemPrice" : 500, "itemGroup" : "sub"},
    {"itemNo" : "gc1028" , "itemName" : "코코넛" , "itemPrice" : 700, "itemGroup" : "sub"},
    {"itemNo" : "gc1029" , "itemName" : "알로에" , "itemPrice" :1000, "itemGroup" : "sub"},
    {"itemNo" : "gc1030" , "itemName" : "얼음 R" , "itemPrice" :0, "itemGroup" : "fre"}, // fre는 가격이 0원
    {"itemNo" : "gc1031" , "itemName" : "얼음 F" , "itemPrice" : 0, "itemGroup" : "fre"},
    {"itemNo" : "gc1032" , "itemName" : "얼음 N" , "itemPrice" : 0, "itemGroup" : "fre"},
    {"itemNo" : "gc1033" , "itemName" : "당도30" , "itemPrice" : 0, "itemGroup" : "fre"},
    {"itemNo" : "gc1034" , "itemName" : "당도50" , "itemPrice" : 0, "itemGroup" : "fre"},
    {"itemNo" : "gc1035" , "itemName" : "당도70" , "itemPrice" : 0, "itemGroup" : "fre"},
    {"itemNo" : "gc1036" , "itemName" : "당도100" , "itemPrice" : 0, "itemGroup" : "fre"},
    {"itemNo" : "gc1037" , "itemName" : "cold포장" , "itemPrice" : 0, "itemGroup" : "fre"},
    {"itemNo" : "gc1038" , "itemName" : "cold매장" , "itemPrice" : 0, "itemGroup" : "fre"},
    {"itemNo" : "gc1039" , "itemName" : "hot포장" , "itemPrice" : 0, "itemGroup" : "fre"},
    {"itemNo" : "gc1040" , "itemName" : "hot매장" , "itemPrice" : 0, "itemGroup" : "fre"},
];  

let memberList =[
    {"memberNo" : 0 , "memberId" : "admin" , "memberPw" : "admin1234", "memberName" : "관리자", "meberSex" : "male","memberTel" : "010-0000-0000", 
    "memberBirth" : 19950506, "memberTelAgency" : "SKT"} , // 통신사 할인이 있어서 통신사 분류도 넣었습니다.
    {"memberNo" : 1 , "memberId" : "hong123" , "memberPw" : "father1234", "memberName" : "홍길동", "meberSex" : "male","memberTel" : "010-2233-1234", 
    "memberBirth" : 19950404, "memberTelAgency" : "SKT"} ,
    {"memberNo" : 2 , "memberId" : "leemalja" , "memberPw" : "lee010010", "memberName" : "이말자", "meberSex" : "female","memberTel" : "010-5564-2562", 
    "memberBirth" : 19670211, "memberTelAgency" : "KT"} ,
    {"memberNo" : 3 , "memberId" : "starsix" , "memberPw" : "star6666", "memberName" : "육성재", "meberSex" : "male","memberTel" : "010-1234-5679", 
    "memberBirth" : 1995002, "memberTelAgency" : "SKT"} ,
    {"memberNo" : 4 , "memberId" : "caster" , "memberPw" : "badgirl444", "memberName" : "박연진", "meberSex" : "female","memberTel" : "010-8533-7412", 
    "memberBirth" : 19851112, "memberTelAgency" : "SKT"} ,
    {"memberNo" : 5 , "memberId" : "teachermoon" , "memberPw" : "victim0101", "memberName" : "문동은", "meberSex" : "female","memberTel" : "010-2587-9632", 
    "memberBirth" : 19850512, "memberTelAgency" : "LG"} ,
    {"memberNo" : 6 , "memberId" : "golfjong" , "memberPw" : "golfowner77", "memberName" : "정재준", "meberSex" : "male","memberTel" : "010-3145-9162", 
    "memberBirth" : 19850102, "memberTelAgency" : "KT"} ,
    {"memberNo" : 7 , "memberId" : "deathson" , "memberPw" : "son8524!", "memberName" : "손명오", "meberSex" : "male","memberTel" : "010-2222-3333", 
    "memberBirth" : 19850407, "memberTelAgency" : "KT"} ,
    {"memberNo" : 8 , "memberId" : "crew" , "memberPw" : "crewjong333", "memberName" : "최혜정", "meberSex" : "female","memberTel" : "010-4567-8820", 
    "memberBirth" : 19850320, "memberTelAgency" : "SKT"} ,
    {"memberNo" : 9 , "memberId" : "druglee" , "memberPw" : "painterdrug00", "memberName" : "이사라", "meberSex" : "female","memberTel" : "010-5426-9541", 
    "memberBirth" : 19850911, "memberTelAgency" : "SKT"} ,
    {"memberNo" : 10 , "memberId" : "goodfather" , "memberPw" : "construction2", "memberName" : "하도영", "meberSex" : "male","memberTel" : "010-2223-5456", 
    "memberBirth" : 19830120, "memberTelAgency" : "LG"} ,
];  

// 금액권 종류
let MoneyCouponList = [
    {"moneyNo" : 1, "moneyType" : 1000},
    {"moneyNo" : 2, "moneyType" : 5000},
    {"moneyNo" : 3, "moneyType" : 10000},
    {"moneyNo" : 4, "moneyType" : 30000},
    {"moneyNo" : 5, "moneyType" : 50000},
    {"moneyNo" : 6, "moneyType" : 100000},
];
let orderList=[
    {"itemNo" : "gc1002", "count": 1, "orderMemberName" : "이사라"},
    {"itemNo" : "gc1003", "count": 2, "orderMemberName" : "하도영"},
    {"itemNo" : "gc1010", "count": 1, "orderMemberName" : "육성재"},
    {"itemNo" : "gc1011", "count": 1, "orderMemberName" : "박연진"},
    {"itemNo" : "gc1003", "count": 3, "orderMemberName" : "홍길동"},
    {"itemNo" : "gc1021", "count": 2, "orderMemberName" : "문동은"},
    {"itemNo" : "gc1011", "count": 1, "orderMemberName" : "정재준"},
    {"itemNo" : "gc1001", "count": 1, "orderMemberName" : "이말자"},
    {"itemNo" : "gc1002", "count": 1, "orderMemberName" : "홍길동"},
    {"itemNo" : "gc1006", "count": 2, "orderMemberName" : "최혜정"},
    {"itemNo" : "gc1024", "count": 1, "orderMemberName" : "박연진"},
    {"itemNo" : "gc1008", "count": 3, "orderMemberName" : "육성재"},
];


